import type { ExtractionDocument } from "./types";

export const MOCK_EXTRACTION: ExtractionDocument = {
  id: "f1",
  fileName: "Kooperativa_Zivot_Smlouva.pdf",
  documentType: "Životní pojištění",
  clientName: "Jan Novák",
  uploadTime: "Dnes, 10:42",
  pageCount: 4,
  globalConfidence: 88,
  reviewStatus: "in_review",
  extractionProvider: "internal",
  processingStatus: "extracted",
  uploadSource: "upload",
  lastProcessedAt: "Dnes, 10:43",
  pdfUrl: "",

  clientMatchCandidates: [
    {
      clientId: "mock-client-1",
      score: 0.94,
      confidence: "high",
      reasons: ["Shoda jména", "Shoda adresy"],
      matchedFields: { pojistnik: true, rc: true },
      displayName: "Jan Novák",
    },
  ],
  draftActions: [],
  isApplied: false,

  executiveSummary:
    "Dokument je životní pojistná smlouva Kooperativy. AI vytěžila 14 z 16 klíčových polí. 2 pole vyžadují ruční kontrolu (měsíční pojistné, invalidita 3. stupeň). Chybí obmyšlená osoba — doporučeno dořešit s klientem.",

  recommendations: [
    {
      id: "rec1",
      type: "warning",
      severity: "high",
      title: "Chybí obmyšlená osoba",
      description:
        "V případě smrti pojistníka spadne pojistné plnění do dědického řízení. Oblast k ověření: doplnění obmyšlené osoby v dokumentu.",
      linkedFieldIds: ["obmyslena"],
      linkedPage: 2,
      actionState: "pending",
      dismissed: false,
      createdAt: "2026-03-24T10:43:00Z",
    },
    {
      id: "rec2",
      type: "insight",
      severity: "high",
      title: "Pojistná částka nepokrývá hypotéku",
      description:
        "Pojistná částka na smrt (2.5M Kč) nepokrývá zůstatek stávající hypotéky klienta (4.2M Kč). Potenciální nesoulad — zvažte revizi s klientem.",
      linkedFieldIds: ["smrt"],
      linkedPage: 1,
      actionState: "pending",
      dismissed: false,
      createdAt: "2026-03-24T10:43:00Z",
    },
    {
      id: "rec3",
      type: "compliance",
      severity: "medium",
      title: "Invalidita 3. stupně nenalezena",
      description:
        "V dokumentu nebyla nalezena informace o krytí invalidity 3. stupně. Ověřte s klientem, zda je toto krytí součástí smlouvy.",
      linkedFieldIds: ["invalidita"],
      linkedPage: 1,
      actionState: "pending",
      dismissed: false,
      createdAt: "2026-03-24T10:43:00Z",
    },
  ],

  diagnostics: {
    ocrQuality: "good",
    extractionCoverage: 87.5,
    totalFields: 16,
    extractedFields: 14,
    unresolvedFieldCount: 2,
    warningCount: 1,
    errorCount: 2,
    conflictingValueCount: 0,
    pagesWithoutReadableText: [],
    notes: [
      "OCR kvalita: dobrá",
      "Strana 2 obsahuje hůře čitelné částky",
      "1 údaj nebyl nalezen v dokumentu",
      "2 hodnoty vyžadují ruční ověření",
    ],
  },

  groups: [
    {
      id: "g1",
      name: "Smluvní strany",
      iconName: "User",
      fields: [
        {
          id: "pojistnik",
          groupId: "g1",
          label: "Pojistník",
          value: "Jan Novák",
          confidence: 99,
          status: "success",
          page: 1,
          sourceType: "ai",
          isConfirmed: false,
          isEdited: false,
          originalAiValue: "Jan Novák",
        },
        {
          id: "rc",
          groupId: "g1",
          label: "Rodné číslo",
          value: "850415/1234",
          confidence: 98,
          status: "success",
          page: 1,
          sourceType: "ai",
          isConfirmed: false,
          isEdited: false,
          originalAiValue: "850415/1234",
        },
        {
          id: "adresa",
          groupId: "g1",
          label: "Adresa",
          value: "Sluneční 145, Praha 4",
          confidence: 95,
          status: "success",
          page: 1,
          sourceType: "ai",
          isConfirmed: false,
          isEdited: false,
          originalAiValue: "Sluneční 145, Praha 4",
        },
      ],
    },
    {
      id: "g2",
      name: "Parametry smlouvy",
      iconName: "FileText",
      fields: [
        {
          id: "pojistovna",
          groupId: "g2",
          label: "Pojišťovna",
          value: "Kooperativa pojišťovna, a.s.",
          confidence: 100,
          status: "success",
          page: 1,
          sourceType: "ai",
          isConfirmed: false,
          isEdited: false,
          originalAiValue: "Kooperativa pojišťovna, a.s.",
        },
        {
          id: "cislo",
          groupId: "g2",
          label: "Číslo smlouvy",
          value: "6543219870",
          confidence: 99,
          status: "success",
          page: 1,
          sourceType: "ai",
          isConfirmed: false,
          isEdited: false,
          originalAiValue: "6543219870",
        },
        {
          id: "pocatek",
          groupId: "g2",
          label: "Počátek pojištění",
          value: "01. 05. 2026",
          confidence: 92,
          status: "success",
          page: 1,
          sourceType: "ai",
          isConfirmed: false,
          isEdited: false,
          originalAiValue: "01. 05. 2026",
        },
        {
          id: "platba",
          groupId: "g2",
          label: "Měsíční pojistné",
          value: "1 450 Kč",
          confidence: 85,
          status: "warning",
          message:
            "Nižší jistota čtení. Zkontrolujte částku v PDF (str. 2).",
          page: 2,
          sourceType: "ai",
          isConfirmed: false,
          isEdited: false,
          originalAiValue: "1 450 Kč",
        },
      ],
    },
    {
      id: "g3",
      name: "Krytá rizika",
      iconName: "Shield",
      fields: [
        {
          id: "smrt",
          groupId: "g3",
          label: "Smrt (Základní částka)",
          value: "2 500 000 Kč",
          confidence: 98,
          status: "success",
          page: 1,
          sourceType: "ai",
          isConfirmed: false,
          isEdited: false,
          originalAiValue: "2 500 000 Kč",
        },
        {
          id: "invalidita",
          groupId: "g3",
          label: "Invalidita 3. stupeň",
          value: "Nenalezeno",
          confidence: 80,
          status: "error",
          message: "Nenalezeno v textu dokumentu.",
          sourceType: "ai",
          isConfirmed: false,
          isEdited: false,
          originalAiValue: "Nenalezeno",
        },
        {
          id: "trvale",
          groupId: "g3",
          label: "Trvalé následky úrazu",
          value: "1 000 000 Kč",
          confidence: 90,
          status: "success",
          page: 1,
          sourceType: "ai",
          isConfirmed: false,
          isEdited: false,
          originalAiValue: "1 000 000 Kč",
        },
      ],
    },
    {
      id: "g4",
      name: "Ostatní ujednání",
      iconName: "Heart",
      fields: [
        {
          id: "obmyslena",
          groupId: "g4",
          label: "Obmyšlená osoba",
          value: "Nevyplněno",
          confidence: 99,
          status: "error",
          message: "Údaj chybí. Nutno dořešit s klientem.",
          page: 2,
          sourceType: "ai",
          isConfirmed: false,
          isEdited: false,
          originalAiValue: "Nevyplněno",
        },
        {
          id: "vinkulace",
          groupId: "g4",
          label: "Vinkulace",
          value: "Ne",
          confidence: 95,
          status: "success",
          page: 2,
          sourceType: "ai",
          isConfirmed: false,
          isEdited: false,
          originalAiValue: "Ne",
        },
      ],
    },
  ],

  extraRecommendations: [
    {
      id: "extra1",
      type: "opportunity",
      severity: "medium",
      title: "Příležitost k revizi invalidního krytí",
      description:
        "Klient nemá pokryté riziko invalidity 3. stupně. Zvažte nabídku rozšíření smlouvy nebo sjednání doplňkového produktu.",
      linkedFieldIds: ["invalidita"],
      actionState: "pending",
      dismissed: false,
      createdAt: "2026-03-24T10:43:00Z",
    },
    {
      id: "extra2",
      type: "next_step",
      severity: "medium",
      title: "Naplánovat servisní schůzku",
      description:
        "Nalezené mezery v krytí — interní návrh: naplánovat servisní schůzku k revizi portfolia (rozhodnutí poradce).",
      linkedFieldIds: [],
      actionState: "pending",
      dismissed: false,
      createdAt: "2026-03-24T10:43:00Z",
    },
    {
      id: "extra3",
      type: "insight",
      severity: "low",
      title: "Srovnání s existujícími smlouvami",
      description:
        "Klient Jan Novák má v CRM další 2 aktivní smlouvy. Interní úkol: porovnat krytí a zkontrolovat duplicity nebo mezery.",
      linkedFieldIds: [],
      actionState: "pending",
      dismissed: false,
      createdAt: "2026-03-24T10:43:00Z",
    },
  ],
};
