ALTER TABLE contacts ADD COLUMN IF NOT EXISTS preferred_channel TEXT;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS do_not_email BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS do_not_push BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS best_contact_time TEXT;
