/**
 * Batch D — CREIF / ATRIS (Realita) / Penta Real Estate Fund (FKI).
 * Kanonické klíče: `creif`, `atris`, `penta` (mapování legacy v `legacy-fund-key-map.ts`).
 * Assety držíme na osvědčených cestách z `public/` (bez nových 404).
 */

import type { BatchASeedRow } from "./base-funds-batch-a.seed";

export const BATCH_D_SEED_ROWS: readonly BatchASeedRow[] = [
  {
    baseFundKey: "creif",
    canonicalName: "CZECH REAL ESTATE INVESTMENT FUND / EFEKTA Real Estate Fund Class CZK",
    displayName: "CREIF",
    provider: "EFEKTA / DRFG",
    manager: "CAIAC Fund Management AG",
    category: "Nemovitostní fond",
    subcategory: "Real assets / retail",
    currency: "CZK",
    isin: "LI0294389098",
    ticker: null,
    riskSRI: null,
    goal:
      "Fond se zaměřuje na investice do stávajících komerčních nemovitostí ve střední Evropě a usiluje o dlouhodobý stabilní výnos s nižší volatilitou než akciové fondy.",
    strategy:
      "Investuje především do fungujících komerčních nemovitostí s nájemními výnosy. Důraz klade na diverzifikaci podle lokality, typu nemovitosti a nájemců; významnou část portfolia tvoří retail a logistika.",
    description:
      "Známý retailový nemovitostní fond používaný v českém poradenství. Výnos je tažený zejména nájemným z komerčních objektů a správou portfolia reálných aktiv. Od ledna 2026 fond oficiálně komunikuje značku EFEKTA Real Estate Fund, ale pro legacy kompatibilitu v Aidvisoře zůstává i značka CREIF.",
    suitable:
      "Pro spíše konzervativní až vyvážené investory, kteří chtějí expozici na komerční nemovitosti bez nutnosti vlastnit konkrétní nemovitost napřímo.",
    horizon: "4+ roky",
    liquidity:
      "Otevřený fond; průběžné vklady i výběry jsou možné, ale podkladová aktiva jsou méně likvidní než ETF nebo peněžní fondy.",
    risks:
      "Riziko poklesu cen nemovitostí, nižší likvidita podkladových aktiv, úvěrové a protistranové riziko, regulatorní změny a koncentrace portfolia do segmentu komerčních nemovitostí.",
    minInvestment: null,
    planningRate: 5,
    officialPerformance: {
      ytd: null,
      oneYear: null,
      threeYearPA: null,
      fiveYearPA: null,
      tenYearPA: null,
      sinceInceptionPA: "5.05% (derived from official 64.52% cumulative since 2016-02-23)",
      asOf: "2026-04-05",
    },
    benefits: [
      "Expozice na portfolio komerčních nemovitostí ve střední Evropě.",
      "Dlouhodobě stabilní výnosový profil založený na nájemném.",
      "Dobře srozumitelný fond pro klienty, kteří chtějí „cihly“ bez přímého vlastnictví nemovitosti.",
    ],
    parameters: {
      fundType: "Otevřený podílový fond / real estate",
      launchDate: "2016-02-23",
      recommendedHorizon: "4 roky",
      officialCumulativeSinceLaunch: "64.52%",
      propertiesValue: "10.48 mld. CZK",
      projectsCount: "26",
      noteOnBrand: "Od 2026-01-19 oficiálně komunikováno jako EFEKTA Real Estate Fund.",
    },
    topHoldings: [
      "Olomouc CITY",
      "SC Haná Olomouc",
      "MMG Centers Szczecin",
      "Retail Park Kutno",
      "JYSK Vyškov",
      "JYSK Jindřichův Hradec",
    ],
    countries: ["Česko", "Polsko"],
    sectors: ["Retail parky a obchodní centra", "Lehká logistika", "Komerční nemovitosti"],
    morningstarRating: null,
    awards: [],
    factsheetUrl: "https://czech-fund.cz/",
    factsheetAsOf: "2026-04-05",
    verifiedAt: "2026-04-05",
    logo: "/logos/creif.png",
    heroImage: "/report-assets/creif/creif-816.jpg",
    galleryImages: [
      "/report-assets/creif/creif-818.jpg",
      "/report-assets/creif/creif-853.jpg",
      "/report-assets/creif/creif-813.jpg",
    ],
    sources: [
      {
        label: "Official product page (current brand)",
        url: "https://czech-fund.cz/",
        kind: "landing_page",
      },
      {
        label: "Official brochure with ISIN and horizon",
        url: "https://czech-fund.cz/wp-content/uploads/2023/08/202510_CZF-CREIF-brozura-CZK-DIP_01_FINAL.pdf",
        kind: "factsheet",
      },
      {
        label: "Official article about rebrand to EFEKTA Real Estate Fund",
        url: "https://czech-fund.cz/",
        kind: "documents",
      },
    ],
    assetTodo: ["logo", "hero", "gallery (commitnuté soubory v public)"],
    notes: [
      "Legacy `productKey` zůstává `creif`; oficiální název zahrnuje EFEKTA Real Estate Fund.",
      "Since inception p.a. je dopočteno z oficiální kumulativní výkonnosti 64.52 % od založení.",
      "planningRate 5 % je interní modelový předpoklad pro projekce, ne oficiální performance.",
    ],
  },
  {
    baseFundKey: "atris",
    canonicalName: "Realita nemovitostní otevřený podílový fond, ATRIS investiční společnost, a.s.",
    displayName: "ATRIS",
    provider: "ATRIS investiční společnost",
    manager: "ATRIS investiční společnost, a.s.",
    category: "Nemovitostní fond",
    subcategory: "Real assets / retail",
    currency: "CZK",
    isin: "CZ0008473139",
    ticker: null,
    riskSRI: 3,
    goal:
      "Fond investuje primárně do komerčních nemovitostí s cílem dlouhodobě udržitelné výnosnosti a stabilního růstu hodnoty podílového listu.",
    strategy:
      "Portfolio staví na prémiových komerčních nemovitostech, dlouhodobých nájemních smlouvách a nízké zadluženosti. Významná je orientace na služby, zdravotnictví, administrativu a vybrané pražské lokality.",
    description:
      "Domácí realitní fond s dlouhou historií a poměrně konzervativním profilem. Atraktivní je kombinace nízkého LTV, vysoké obsazenosti a dlouhých nájemních smluv.",
    suitable:
      "Pro klienty, kteří chtějí realitní složku portfolia se stabilnější volatilitou než akcie a preferují český fond s fyzickými nemovitostmi.",
    horizon: "min. 5 let",
    liquidity: "Otevřený fond; hodnota podílového listu se stanovuje měsíčně.",
    risks:
      "Riziko nižší likvidity realitních aktiv, poklesu cen komerčních nemovitostí, koncentrace na vybrané sektory a města a riziko spojené s nájemci a obsazeností.",
    minInvestment: "od 500 Kč",
    planningRate: 5,
    officialPerformance: {
      ytd: "0.31%",
      oneYear: "4.02%",
      threeYearPA: null,
      fiveYearPA: null,
      tenYearPA: null,
      sinceInceptionPA: "4.71%",
      asOf: "2026-02-28",
    },
    benefits: [
      "Nízké LTV a vysoká obsazenost portfolia.",
      "Dlouhodobé nájemní smlouvy s WAULT 7.7 roku.",
      "Historie fondu od roku 2009 a zaměření na reálná aktiva.",
    ],
    parameters: {
      fundType: "Speciální fond nemovitostí, OPF",
      depositary: "Československá obchodní banka, a.s.",
      launchDate: "2009-04-27",
      minimumInvestment: "500 Kč",
      managementFee: "1.60 % z výše vlastního kapitálu",
      valuationFrequency: "měsíčně",
      officialNAV: "2.1607 CZK",
      assets: "6 879 693 294 Kč",
      equity: "6 672 830 233 Kč",
      ltv: "28.82%",
      occupancy: "99%",
      wault: "7.7 let",
      portfolioProperties: "15",
    },
    topHoldings: [
      "Obchodní dům Máj na Národní třídě",
      "Palác Bristol v centru Prahy",
      "Delta Ruzyně",
      "Prémiové komerční nemovitosti v Praze",
      "Nemovitosti se zaměřením na služby a zdravotnictví",
    ],
    countries: ["Česko"],
    sectors: ["Služby", "Maloobchod", "Administrativa", "Výroba", "Zdravotnictví"],
    morningstarRating: null,
    awards: [],
    factsheetUrl: "https://storage.atrisinvest.cz/actual/ATRIS_factsheet.pdf",
    factsheetAsOf: "2026-02-28",
    verifiedAt: "2026-04-05",
    logo: "/logos/atris.png",
    heroImage: "/report-assets/atris/atris1.jpg",
    galleryImages: [
      "/report-assets/atris/atris2.jpg",
      "/report-assets/atris/atris3.jpg",
      "/report-assets/atris/atris4.jpg",
    ],
    sources: [
      {
        label: "Official fund page",
        url: "https://www.atrisinvest.cz/fond-realita/",
        kind: "landing_page",
      },
      {
        label: "Official value/performance page",
        url: "https://www.atrisinvest.cz/fond-realita/hodnota-podiloveho-listu/",
        kind: "factsheet",
      },
      {
        label: "Official properties page",
        url: "https://www.atrisinvest.cz/nemovitosti/",
        kind: "documents",
      },
    ],
    assetTodo: ["logo", "hero", "gallery (commitnuté soubory v public)"],
    notes: [
      "Jeden kanonický záznam `atris`; lump vs. monthly řeší `InvestmentEntry.type`, ne duplicitní base fondy.",
      "Alias `atris_realita` → `atris` v legacy mapě pro starší exporty.",
      "planningRate 5 % je interní modelový předpoklad pro projekce, ne oficiální performance.",
    ],
  },
  {
    baseFundKey: "penta",
    canonicalName: "Penta Real Estate Fund SICAV, a.s. – Penta Real Estate podfond",
    displayName: "Penta",
    provider: "Penta Fund",
    manager: "CODYA investiční společnost, a.s.",
    category: "Fond kvalifikovaných investorů",
    subcategory: "Real estate / qualified investors",
    currency: "CZK",
    isin: "CZ0008053691",
    ticker: null,
    riskSRI: 6,
    goal:
      "Podfond usiluje o zhodnocování investovaných prostředků zejména prostřednictvím majetkové účasti ve společnosti PENTA REAL ESTATE HOLDING LIMITED a souvisejících real estate projektech skupiny Penta.",
    strategy:
      "Fond kombinuje hotové výnosové nemovitosti a development projekty skupiny Penta Real Estate. Investice je určena kvalifikovaným investorům a počítá s delším horizontem a vyšší rizikovostí než retailové realitní fondy.",
    description:
      "Alternativní real estate fond kvalifikovaných investorů navázaný na developerský ekosystém Penty v Česku a na Slovensku. Je vhodný spíše jako doplněk bohatších klientských portfolií než jako mainstream retailová volba.",
    suitable:
      "Pro kvalifikované investory, kteří chtějí expozici na development a prémiové nemovitosti skupiny Penta a akceptují vyšší riziko i delší likviditu.",
    horizon: "5+ let",
    liquidity:
      "Měsíční oceňování; odkup je možný, ale vypořádání může podle dokumentace trvat až 24 měsíců od konce oceňovacího období.",
    risks:
      "Vyšší rizikovost alternativního fondu, koncentrace na realitní projekty skupiny Penta, omezená likvidita, použití leverage a rizika developmentu a ekonomického cyklu.",
    minInvestment: "od 1 000 000 Kč / 50 000 EUR",
    planningRate: 13,
    officialPerformance: {
      ytd: null,
      oneYear: null,
      threeYearPA: null,
      fiveYearPA: null,
      tenYearPA: null,
      sinceInceptionPA: null,
      asOf: "2026-04-05",
    },
    benefits: [
      "Přístup k development a real estate portfoliu skupiny Penta.",
      "Potenciálně vyšší výnosový profil než u retailových realitních fondů.",
      "Dává smysl jako specializovaná alternativní složka pro bonitnější klienty.",
    ],
    parameters: {
      fundType: "Qualified investor fund / SICAV sub-fund",
      subFundLaunch: "2024-10-24",
      cnbRegistrationFund: "2024-10-07",
      cnbRegistrationSubFund: "2024-10-30",
      targetYield: "13 - 15 % p.a.",
      minimumInvestment: "1 000 000 Kč / 50 000 EUR",
      portfolioGrossAssetValue: "€1.75B",
      managementFeeCurrentClassD: "1.6 % p.a.",
      recommendedHoldingPeriod: "5 let",
      redemptionSettlement: "až 24 měsíců",
      entryFeeMax: "5%",
      exitFee: "až 20 % v prvních 3 letech, poté 0 %",
    },
    topHoldings: [
      "Masaryčka",
      "Nová Waltrovka",
      "Florenc 21",
      "4. kvadrant",
      "Nuselský pivovar",
      "Vinohradská 8",
      "Rezidence Petrská",
      "Southbank",
      "Chalupkova",
      "Vajnorská",
      "Medze",
    ],
    countries: ["Česko", "Slovensko"],
    sectors: ["Commercial real estate", "Residential real estate", "Development"],
    morningstarRating: null,
    awards: ["Masaryčka – nejlepší stavba roku 2024 (uvedeno v term sheetu / dokumentaci)"],
    factsheetUrl: "https://www.pentafund.com/storage/FACTSHEET_Penta-Real-Estate-Fund_CZ.pdf",
    factsheetAsOf: "2026-04-05",
    verifiedAt: "2026-04-05",
    logo: "/logos/Penta.png",
    galleryImages: [
      "/report-assets/penta/penta1.png",
      "/report-assets/penta/penta2.jpg",
      "/report-assets/penta/penta3.webp",
    ],
    sources: [
      {
        label: "Official product page",
        url: "https://www.pentafund.com/penta-real-estate-fund/",
        kind: "landing_page",
      },
      {
        label: "Official Czech factsheet",
        url: "https://www.pentafund.com/storage/FACTSHEET_Penta-Real-Estate-Fund_CZ.pdf",
        kind: "factsheet",
      },
      {
        label: "Official KID Class D",
        url: "https://www.pentafund.com/storage/KID-Class-D_Penta-Real-Estate-Fund_EN.pdf",
        kind: "kid",
      },
      {
        label: "Official statute / term sheet reference",
        url: "https://www.pentafund.com/storage/STATUT_Penta-Real-Estate-Fund_CZ.pdf",
        kind: "documents",
      },
    ],
    assetTodo: ["logo", "hero", "gallery (commitnuté soubory v public)"],
    notes: [
      "Tag `qualified_investor` v availability — filtrování FKI; oddělená UI skupina „FKI / alternativní“.",
      "Oficiální historická performance v seedu záměrně null; target yield není performance.",
      "planningRate 13 % je interní modelový předpoklad odvozený z pásma 13–15 % p.a., ne historická výkonnost.",
      "Alias `penta_real_estate_fund` → `penta` pro importy ze seed dokumentů.",
    ],
  },
];
